# Generated by Django 5.0.4 on 2024-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settleup',
            name='account_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='settleup',
            name='bank',
            field=models.CharField(default='', max_length=10),
        ),
    ]
