# Generated by Django 5.0.4 on 2024-06-12 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_settleup_account_no_settleup_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settleup',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settle', to='boards.meeting'),
        ),
    ]
